[package]
name = "rust-audio-poc"
version = "0.1.0"
authors = ["Riley Mathews <rileymathews80@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portaudio = "0.7.0"
three = "0.4.0"
